- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: cluster
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- resources:
    label: homepage
    cpu: true
    memory: true

- search:
    provider: duckduckgo
    target: _blank
