- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: cluster
    nodes:
      show: false

- search:
    provider: duckduckgo
    target: _blank
