version: "3.9"

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8080
    ports:
      - "8080:8080"
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
    networks:
      - shared

  home-root:
    build:
      context: ./apps/home-root
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.home-root.rule=PathPrefix(`/`)
      - traefik.http.routers.home-root.priority=1
      - traefik.http.routers.home-root.entrypoints=web
      - traefik.http.services.home-root.loadbalancer.server.port=8080
    networks:
      - shared

networks:
  shared:
    mode: bridge


