apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/fluxcd/flux2/releases/download/v2.9.4/install.yaml
  - ./sync/git-repository.yaml
  - ./sync/kustomization.yaml
  - ./sync/oci-repository.yaml
  - ./sync/kustomization-setup.yaml
  - ./sync/kustomization-home.yaml
  - ./sync/kustomization-internal.yaml
