apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: smtp-relay
  labels:
    app: smtp-relay
spec:
  selector:
    app: smtp-relay
  ports:
    - name: smtp
      port: 587
      targetPort: smtp
