apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "Europe/London"
          volumeMounts:
            - mountPath: /config
              name: config
              subPath: config
            - mountPath: /metadata
              name: config
              subPath: metadata
            - mountPath: /audiobooks
              name: media
        - name: libation
          image: rmcrackan/libation:latest
          env:
            - name: TZ
              value: "Europe/London"
            - name: SLEEP_TIME
              value: "1h"
          volumeMounts:
            - mountPath: /config
              name: libation-config
            - mountPath: /data
              name: media
              subPath: audible
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: media
          persistentVolumeClaim:
            claimName: audiobookshelf-media
        - name: libation-config
          persistentVolumeClaim:
            claimName: audiobookshelf-libation-config
