---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-config
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvm-data
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-media
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvm-data
  resources:
    requests:
      storage: 50Gi
