---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lldap
  namespace: lldap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvm-data
  resources:
    requests:
      storage: 128Mi
