---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-root-deployment
  labels:
    app: home-root
  namespace: home
spec:
  selector:
    matchLabels:
      app: home-root
  template:
    metadata:
      labels:
        app: home-root
    spec:
      containers:
      - name: home-root
        image: ticklethepanda/home-root:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        env:
        - name: NGINX_PORT
          value: "8080"
        volumeMounts:
        - mountPath: /var/cache/nginx/
          name: nginx-temp
        - mountPath: /var/run/
          name: nginx-run
      volumes:
        - emptyDir: {}
          name: nginx-temp
        - emptyDir: {}
          name: nginx-run
