---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dns-pv
  namespace: pihole
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disk/pihole-dns
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-manager-1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-dns
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: pihole-dns-pv
  resources:
    requests:
      storage: 128Mi
