---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speed-test-deployment
  labels:
    app: speed-test
  namespace: home
spec:
  selector:
    matchLabels:
      app: speed-test
  template:
    metadata:
      labels:
        app: speed-test
    spec:
      containers:
      - name: speed-test
        image: ticklethepanda/speed-tester:latest
        env:
        - name: SPEED_TEST_SITE_ROOT
          value: "/speed-test"
        - name: SPEED_TEST_EMAIL_THRESHOLD
          value: "25"
        - name: SPEED_TEST_SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-api-key
              key: key
        - name: SPEED_TEST_EMAIL_FROM
          valueFrom:
            secretKeyRef:
              name: speed-test-emails
              key: from
        - name: SPEED_TEST_EMAIL_TO
          valueFrom:
            secretKeyRef:
              name: speed-test-emails
              key: to
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /data
          name: speed-test-volume
        - mountPath: /tmp
          name: tmp
        - mountPath: /.cache
          name: cache
      volumes:
        - name: speed-test-volume
          persistentVolumeClaim:
            claimName: speed-test-pvc
        - emptyDir: {}
          name: tmp
        - emptyDir: {}
          name: cache
