---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelapse-deployment
  labels:
    app: timelapse
  namespace: home
spec:
  selector:
    matchLabels:
      app: timelapse
  template:
    metadata:
      labels:
        app: timelapse
    spec:
      containers:
      - name: timelapse
        image: ticklethepanda/rpi-timelapse:latest
        env:
        - name: RPI_CAMERA_SITE_ROOT
          value: "/timelapse"
        - name: RPI_CAMERA_STORAGE_DIR
          value: "/data"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: timelapse-volume
        - mountPath: /dev/vcsm-cma
          name: timelapse-vcsm-cma
        - mountPath: /dev/vchiq
          name: timelapse-vchiq
      securityContext:
        privileged: true
      tolerations:
      - key: "pi-camera"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
        - name: timelapse-volume
          persistentVolumeClaim:
            claimName: timelapse-pvc
        - name: timelapse-vcsm-cma
          hostPath:
            path: /dev/vcsm-cma
        - name: timelapse-vchiq
          hostPath:
            path: /dev/vchiq
