#!/usr/bin/env bash

TIME=$(date -I)
DIR="convert/$TIME"
SERVER=k8s-node-camera-1
REMOTE_DIR=/mnt/disk/timelapse/$1/images/*
FILE_TYPE='*'
MENCODER_FILES="mf://$DIR/$FILE_TYPE"

mkdir -p $DIR

rsync -au $SERVER:$REMOTE_DIR $DIR

mencoder $MENCODER_FILES -mf w=800:h=600:fps=2:type=png -ovc copy -oac copy -o "$DIR/output.avi"
