// Code generated by "stringer -type=RecentPeriod"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Month-0]
	_ = x[Week-1]
	_ = x[Day-2]
}

const _RecentPeriod_name = "MonthWeekDay"

var _RecentPeriod_index = [...]uint8{0, 5, 9, 12}

func (i RecentPeriod) String() string {
	if i < 0 || i >= RecentPeriod(len(_RecentPeriod_index)-1) {
		return "RecentPeriod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RecentPeriod_name[_RecentPeriod_index[i]:_RecentPeriod_index[i+1]]
}
