apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploys into the external-dns namespace (created by ../externaldns) so it can
# mount the shared externaldns-tsig secret.
namespace: external-dns

resources:
  - ./rbac.yaml
  - ./deployment.yaml
  - ./records.yaml
