resource "cloudflare_zero_trust_tunnel_cloudflared" "home" {
  account_id = var.account_id
  name       = "home"
  config_src = "cloudflare"
}

import {
  to = cloudflare_zero_trust_tunnel_cloudflared.home
  id = "4611a7a2299c655529452ac81b5f4844/163b6194-178f-4910-9e53-cc2f46344754"
}

# Ingress rules the "home" tunnel proxies, plus the private-network routing
# CI and the router's dashboard-side use to reach the LAN (see routes below).
resource "cloudflare_zero_trust_tunnel_cloudflared_config" "home" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.home.id
  source     = "cloudflare"

  config = {
    ingress = [
      {
        hostname = "home.ticklethepanda.co.uk"
        service  = "http://traefik-external.kube-system"
        origin_request = {
          http_host_header = "home.ticklethepanda.co.uk"
        }
      },
      {
        hostname = "ha.ticklethepanda.co.uk"
        service  = "https://192.168.1.5"
        origin_request = {
          http_host_header   = "ha.ticklethepanda.co.uk"
          origin_server_name = "ha.internal.ticklethepanda.co.uk"
        }
      },
      {
        service = "http_status:404"
      },
    ]
    warp-routing = {
      enabled = true
    }
  }
}

import {
  to = cloudflare_zero_trust_tunnel_cloudflared_config.home
  id = "4611a7a2299c655529452ac81b5f4844/163b6194-178f-4910-9e53-cc2f46344754"
}

resource "cloudflare_zero_trust_tunnel_cloudflared_virtual_network" "default" {
  account_id         = var.account_id
  name               = "default"
  comment            = "This network was autogenerated because this account lacked a default one"
  is_default_network = true
}

import {
  to = cloudflare_zero_trust_tunnel_cloudflared_virtual_network.default
  id = "4611a7a2299c655529452ac81b5f4844/fb55ae05-be19-4c55-b17d-de09fa2b3016"
}

# CI's own path into the LAN -- see CLAUDE.md "Node pattern" / "Router pattern".
resource "cloudflare_zero_trust_tunnel_cloudflared_route" "homelab_vlan" {
  account_id         = var.account_id
  tunnel_id          = cloudflare_zero_trust_tunnel_cloudflared.home.id
  virtual_network_id = cloudflare_zero_trust_tunnel_cloudflared_virtual_network.default.id
  network            = "192.168.1.0/24"
  comment            = "homelab vlan"
}

import {
  to = cloudflare_zero_trust_tunnel_cloudflared_route.homelab_vlan
  id = "4611a7a2299c655529452ac81b5f4844/f2a570ed-f51d-409f-8a10-a714dadba9c6"
}

resource "cloudflare_zero_trust_tunnel_cloudflared_route" "trusted_vlan" {
  account_id         = var.account_id
  tunnel_id          = cloudflare_zero_trust_tunnel_cloudflared.home.id
  virtual_network_id = cloudflare_zero_trust_tunnel_cloudflared_virtual_network.default.id
  network            = "192.168.10.0/24"
  comment            = "trusted vlan"
}

import {
  to = cloudflare_zero_trust_tunnel_cloudflared_route.trusted_vlan
  id = "4611a7a2299c655529452ac81b5f4844/66aeac49-881e-4ace-a7d9-e73158c02c75"
}
