apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: speed-test

namePrefix: speed-test-
commonLabels:
  app: speed-test

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./volume.yaml
  - ./volume-claim.yaml
  - ./ingress.yaml
