apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.45.0
          args:
            - "-in-cluster"
            - "-unsafe-use-service-account-token"
          ports:
            - name: http
              containerPort: 4466
          env:
            - name: TZ
              value: "Europe/London"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 15m
              memory: 48Mi
            limits:
              memory: 192Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 101
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
