version: "3.8"
services:
  my-service:
    container_name: speed-tester
    build:
      context: .
      target: dev
    volumes:
    - .:/app:rw,delegated
    - ./data:/data
    environment:
    - SPEED_TEST_SITE_ROOT=/speed-test
    - SPEED_TEST_SHARED_ASSETS_SITE=http://localhost:8080
    - SPEED_TEST_EMAIL_CRON=* * * * *
    env_file: .env
    ports:
    - 10000:10000
    - 2345:2345
