apiVersion: v1
kind: Service
metadata:
  name: kube-api-lb
  annotations:
    metallb.universe.tf/address-pool: kube-api
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.3
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: kube-api-proxy
    
