apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: timelapse

namePrefix: timelapse-
commonLabels:
  app: timelapse

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./volume.yaml
  - ./volume-claim.yaml
  - ./ingress.yaml
