apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: label-studio
  namespace: label-studio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
