apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns

resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml

configMapGenerator:
  - name: coredns-config
    files:
      - Corefile
      - zones/internal.ticklethepanda.co.uk.zone
