#!/bin/sh
# Keep every management surface on the LAN. The wan zone is already
# input DROP (script 50), this is the second line of defence: bind the
# services themselves to the LAN address.

uci set dropbear.@dropbear[0].Interface='lan'
uci set dropbear.@dropbear[0].Port='22'
uci set dropbear.@dropbear[0].PasswordAuth='on'
uci set dropbear.@dropbear[0].RootPasswordAuth='on'
uci commit dropbear

uci -q delete uhttpd.main.listen_http
uci -q delete uhttpd.main.listen_https
uci add_list uhttpd.main.listen_http='192.168.1.1:80'
uci add_list uhttpd.main.listen_https='192.168.1.1:443'
uci commit uhttpd
