apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sync-orchestrator
  namespace: audiobookshelf
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://audiobooks-sync.internal.ticklethepanda.co.uk
    gethomepage.dev/name: Audiobooks Sync
    gethomepage.dev/group: Media
    gethomepage.dev/icon: mdi-sync
    gethomepage.dev/description: Libation / Libro.fm sync
spec:
  entryPoints:
    - int-web-secure
  tls: {}
  routes:
    - kind: Rule
      match: Host(`audiobooks-sync.internal.ticklethepanda.co.uk`)
      middlewares:
        - name: tinyauth
          namespace: tinyauth
      services:
        - name: sync-orchestrator
          namespace: audiobookshelf
          port: 80
