apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: root

namePrefix: home-root-
commonLabels:
  app: home-root

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
