apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ./apps/audiobookshelf
- ./apps/label-studio
- ./auth/lldap
- ./auth/pocketid
- ./auth/tinyauth
- ./index
- ./network/bind
- ./network/coredns
- ./network/externaldns
- ./network/dhcp-kea
- ./network/pihole
- ./network/unbound
- ./services/mosquitto
- ./services/postgres
