apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ./audiobookshelf
- ./dns
- ./index
- ./kea
- ./label-studio
- ./lldap
- ./mosquitto
- ./pihole
- ./pocketid
- ./postgres
- ./tinyauth
- ./unbound
