apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: unbound
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: klutchell/unbound:1.26.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 96Mi
          ports:
            - containerPort: 5335
              name: dns-udp
              protocol: UDP
            - containerPort: 5335
              name: dns-tcp
              protocol: TCP
          volumeMounts:
            - name: unbound-config
              mountPath: /etc/unbound/custom.conf.d/home-dns.conf
              subPath: home-dns.conf
              readOnly: true
      volumes:
        - name: unbound-config
          configMap:
            name: unbound-config
