apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: unbound
spec:
  type: ClusterIP
  clusterIP: 10.43.53.54
  selector:
    app: unbound
  ports:
    - name: dns-udp
      port: 53
      targetPort: 5335
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 5335
      protocol: TCP
