apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - ./namespace.yaml
  - ./volume-conf.yaml
  - ./volume-dns.yaml
  - ./deployment.yaml
  - ./service-lb.yaml
  - ./service.yaml
  - ./ingress.yaml

configMapGenerator:
  - name: pihole-config
    envs:
      - pihole.env
    files:
      - FTLCONF_dns_hosts=dns-hosts.txt
      - FTLCONF_dns_upstreams=dns-upstreams.txt
      - FTLCONF_dns_revServers=dns-revservers.txt
