---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole-dns
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvm-data
  resources:
    requests:
      storage: 128Mi
