apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./self.yaml
  - ./oci-repository.yaml
  - ./kustomization-setup.yaml
  - ./kustomization-setup-config.yaml
  - ./kustomization-home.yaml
  - ./kustomization-internal.yaml
