name: Build and deploy speed-test

on:
  push:
    branches: main
    paths:
    - speed-tester/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Connect to Cloudflare Warp
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: ticklethepanda
          auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build the image
        run: |
          docker buildx build --push \
          --tag ticklethepanda/speed-tester:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 ./speed-tester/
      - name: Setup k8s context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Rollout latest image
        run: kubectl rollout restart deployment/speed-test-deployment --namespace=home
