name: Update k8s

on:
  push:
    branches: main
    paths:
      - .github/workflows/deploy.yaml
      - deploy/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Connect to Cloudflare Warp
        uses: Boostport/setup-cloudflare-warp@v1
        with:
          organization: ticklethepanda
          auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup k8s context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy cluster
        run: kubectl apply -k deploy
