name: Update k8s

on:
  push:
    branches: main
    paths:
      - deploy/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup k8s context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy cluster setup
        run: kubectl apply -k deploy/setup
      - name: Deploy apps
        run: kubectl apply -f deploy
